AWSTemplateFormatVersion: "2010-09-09"
Description: dev-test
Parameters:
  Subnet1:
    Type: String
    Description: Subnet IDs for VPC
    Default: 'subnet-013e7448'
  Subnet2:
    Type: String
    Description: Subnet IDs for VPC
    Default: 'subnet-bdc65be6'
  SecurityGroup:
    Type: String
    Default: 'sg-b2c2cece'
    Description: SecurityGroup
  VPC:
    Type: String
    Default: 'vpc-40c06426'
    Description: VPCID

Resources:
  test:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-097104a26f5e1c26a" # Rocky 8 Official us-east-1
      InstanceType: t2.small
      KeyName: dev-key
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          SubnetId: !Ref Subnet1
          GroupSet: [ !Ref SecurityGroup ]
      Tags:
        - Key: "Name"
          Value: "dev-test"
      UserData:
        Fn::Base64: |
            #!/bin/bash
            hostnamectl set-hostname test
            echo "preserve_hostname: true" >> /etc/cloud/cloud.cfg
            sed -i 's/SELINUX=enforcing/SELINUX=disabled/' /etc/selinux/config
            # install
            yum -y install curl vim bash-completion httpd
            systemctl enable httpd
            shutdown -r now
